# Generated by Django 4.1.4 on 2022-12-30 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_item_text', models.CharField(max_length=100, verbose_name='Название пунтка меню')),
                ('link', models.URLField()),
                ('sub_menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draw_menu.menuitem', verbose_name='Подпункт меню')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draw_menu.menuitem', verbose_name='Пункт меню')),
            ],
        ),
    ]
