# Generated by Django 4.1.4 on 2023-01-02 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_item_text', models.CharField(max_length=100, verbose_name='Название пунтка меню')),
                ('link', models.URLField(blank=True)),
                ('menu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draw_menu.menu', verbose_name='Меню')),
                ('parent_menu_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_menu_item', to='draw_menu.menuitem', verbose_name='Родительский подпункт меню')),
            ],
        ),
    ]
